// Abilities Action Types
export const FETCH_ABILITIES_REQUEST = 'FETCH_ABILITIES_REQUEST';
export const FETCH_ABILITIES_SUCCESS = 'FETCH_ABILITIES_SUCCESS';
export const FETCH_ABILITIES_FAILURE = 'FETCH_ABILITIES_FAILURE';
// Loading Screen Action Types
export const SET_LOADING_TEXT = 'SET_LOADING_TEXT';
export const SET_QUESTIONS_COMPLETED = 'SET_QUESTIONS_COMPLETED';
// Pokemon Action Types
export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_FAILURE = 'FETCH_POKEMON_FAILURE';
export const UPDATE_POKEMON_STATUS = 'UPDATE_POKEMON_STATUS';
// User Action Types
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_ID = 'SET_USER_ID';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
// Moves Action Types
export const FETCH_MOVES_REQUEST = 'FETCH_MOVES_REQUEST';
export const FETCH_MOVES_SUCCESS = 'FETCH_MOVES_SUCCESS';
export const FETCH_MOVES_FAILURE = 'FETCH_MOVES_FAILURE';
// Species Action Types
export const FETCH_SPECIES_REQUEST = 'FETCH_SPECIES_REQUEST';
export const FETCH_SPECIES_SUCCESS = 'FETCH_SPECIES_SUCCESS';
export const FETCH_SPECIES_FAILURE = 'FETCH_SPECIES_FAILURE';
// PokeGrower Action Types
export const FETCH_POKEGROWER_REQUEST = 'FETCH_POKEGROWER_REQUEST';
export const FETCH_POKEGROWER_SUCCESS = 'FETCH_POKEGROWER_SUCCESS';
export const FETCH_POKEGROWER_FAILURE = 'FETCH_POKEGROWER_FAILURE';
export const POKEGROWER_INCREMENT = 'POKEGROWER_INCREMENT';