// Abilities Action Types
export const FETCH_ABILITIES_REQUEST = 'FETCH_ABILITIES_REQUEST';
export const FETCH_ABILITIES_SUCCESS = 'FETCH_ABILITIES_SUCCESS';
export const FETCH_ABILITIES_FAILURE = 'FETCH_ABILITIES_FAILURE';
// Loading Screen Action Types
export const SET_LOADING_TEXT = 'SET_LOADING_TEXT';
export const SET_QUESTIONS_COMPLETED = 'SET_QUESTIONS_COMPLETED';
// Pokemon Action Types
export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_FAILURE = 'FETCH_POKEMON_FAILURE';
export const UPDATE_POKEMON_STATUS = 'UPDATE_POKEMON_STATUS';
// User Action Types
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_ID = 'SET_USER_ID';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';