// PokeGrower Action Types
export const FETCH_POKEGROWER_REQUEST = 'FETCH_POKEGROWER_REQUEST';
export const FETCH_POKEGROWER_SUCCESS = 'FETCH_POKEGROWER_SUCCESS';
export const FETCH_POKEGROWER_FAILURE = 'FETCH_POKEGROWER_FAILURE';
export const POKEGROWER_INCREMENT_CURRENCY = 'POKEGROWER_INCREMENT_CURRENCY';
// Purchase Upgrades Action Types
export const PURCHASE_UPGRADE = 'PURCHASE_UPGRADE';